SELECT * FROM DBO.TBCIDADE
SELECT NOME_CIDADE FROM DBO.TBCIDADE
SELECT * FROM DBO.TBCIDADE WHERE ID_CIDADE>3
SELECT * FROM DBO.TBCIDADE WHERE NOME_CIDADE='sorocaba'
SELECT * FROM DBO.TBCIDADE WHERE NOME_CIDADE LIKE '%A'
SELECT * FROM DBO.TBCIDADE WHERE NOME_CIDADE LIKE 'A%'
SELECT * FROM DBO.TBCIDADE WHERE NOME_CIDADE LIKE '%A%'
INSERT INTO DBO.TBCIDADE VALUES ('UBATUBA', 'SP')
UPDATE DBO.TBCIDADE SET NOME_CIDADE='NOVA' WHERE ID_CIDADE=4
DELETE FROM DBO.TBCIDADE WHERE ID_CIDADE=23

